---
title: Guess the flag
hero_image: afbeeldingen / banner.png
description: Create a flag quiz game to yourself and your friends!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Draw the flags
  - 
    title: Create a list of flags
  - 
    title: Choose random flags
  - 
    title: Choose a correct answer
  - 
    title: Show the flags
  - 
    title: Ask the question
  - 
    title: Check the answer
  - 
    title: 'Uitdaging: meer objecten'
  - 
    title: Start a new round
  - 
    title: "Challenge: improve the game"
    challenge: true
  - 
    title: Wat kun je verder nog doen?
