title: Guess the flag
hero_image: images/banner.png
description: How good is your flag knowledge? Create a flag quiz game—click the right flag to score points
theme: navy # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4.0.1
last_tested: 2018-02-01
steps: 
- title: Introduction
- title: What you will need
- title: Draw the flags
- title: Create a list of flags
- title: Choose random flags
- title: Choose a correct answer
- title: Show the flags
- title: Ask the question
- title: Check the answer
- title: Add a score
- title: Start a new round
- title: "Challenge: Improve the game"
