---
title: Errate die Flagge
hero_image: images/banner.png
description: Erstelle ein Flaggen-Quiz für dich und deine Freunde!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-10-23
steps:
- title: Einleitung
  completion: engaged
- title: Zeichne die Flaggen
- title: Erstelle eine Liste der Flaggen
- title: Wähle zufällige Flaggen aus
- title: Wähle eine richtige Antwort aus
- title: Zeige die Flaggen
- title: Stelle eine Frage
- title: Überprüfe die Antwort
- title: Füge Punkte hinzu
  completion: internal
- title: Starte eine neue Runde
- title: 'Herausforderung: Verbessere das Spiel'
  challenge: true
- title: Was kommt als nächstes?
