---
title: Devine le drapeau
hero_image: images/banner.png
description: Créer un quiz de drapeau pour toi et tes amis !
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-10-23
steps:
- title: Introduction
- title: Dessiner les drapeaux
- title: Créer une liste de drapeaux
  completion:
  - engaged
- title: Choisir des drapeaux aléatoires
- title: Choisir une réponse correcte
- title: Afficher les drapeaux
- title: Poser la question
- title: Vérifier la réponse
- title: Ajouter un score
- title: Commencer une nouvelle partie
  completion:
  - internal
- title: 'Défi : améliorer le jeu'
  challenge: true